// helper functions for the solar panel simulation used in simulate.js

import { panelArea, solarPanelEfficiency, tankVolume, waterHeatCapacity } from "./constants";

// function to calculate power generated by the solar panel: P = eta * G * A
export function calculateSolarPower(averageSolarIrradiance) {
    return solarPanelEfficiency * averageSolarIrradiance * panelArea; // [Watts]
}

// function to calculate energy transferred to the water for a given time step: E = P * delta_T
export function calculateEnergyProduced(power, timeStepSeconds) {
    return power * timeStepSeconds; // [Joules]
}

// function to calculate the temperature increase in the water: delta_T = E / (m * c)
export function calculateTemperatureIncrease(energy, currentTemperature) {
    let tempIncrease = currentTemperature + energy / (tankVolume * waterHeatCapacity); // °C
    return tempIncrease; // [°C]
}

// function to simulate the tank water mixing with the new (hot) water from solar panel
export function mixTankWater(oldTemp, newTemp) {
    return (oldTemp + newTemp) / 2; // °C
}

